GET {{endpoint}}/hello

###
@endpoint = https://918chlxk51.execute-api.eu-central-1.amazonaws.com/prod

# @cardId = 240a5f22-d438-44fd-a0e1-4170a72f7e71
@token = -EUkC6SRPdNdHXWNv-Xc39QQhJr7VDKkpd9HYdcki-Nl3hBhgfeHERpU1jSisRUaw3qWW5ozbmp9ApDqKEguOm7l4RY2RWCOnqauSIaC0sMv21Dpu0ZnEx6XmYV8s8A4ODoUc9TMLr9CS4Qe9SdMLt8HxGYgPQ
###

# @name getCards
GET {{endpoint}}/cards
Content-Type: application/json
Accept: application/json
Authorization: {{token}}



###
@cardId = {{getCards.response.body.$.Items[0].$.cardId}}
GET {{endpoint}}/cards?cardId={{cardId}}
Content-Type: application/json

###
GET {{endpoint}}/cards?location=Ternopil
Content-Type: application/json

###
DELETE {{endpoint}}/cards?cardId={{cardId}}
Content-Type: application/json

###
POST {{endpoint}}/cards/
Content-Type: application/json

{
  "location": "Lviv",
  "name": "place cofee drink"
}

###
PUT {{endpoint}}/cards/cardId={{cardId}}
Content-Type: application/json

{
  "location": "my lovely city"
}
