@endpoint = https://918chlxk51.execute-api.eu-central-1.amazonaws.com/prod
GET {{endpoint}}/hello/
###

GET {{endpoint}}/cards/
Content-Type: application/json

###
GET {{endpoint}}/cards?cardId=b55ff89c-da8f-48c4-a4ea-7bda14d64eca
Content-Type: application/json

###
POST {{endpoint}}/cards/
Content-Type: application/json

{
  "location": "Lviv new task",
  "name": "Best location"
}
